### ISSUE TITLE
Move config options to app.config instead of the Express app object.

### ISSUE THREAD

**Issue by ekryski** [feathersjs/configuration#31]
In order to decouple us from Express we might want to namespace config options to `app.config` instead of using [`app.set()`](https://github.com/feathersjs/feathers-configuration/blob/master/src/index.js#L55) and `app.get()`. The rationale: 

1. node-config already exposes the `.get` and `.set` functionality
2. with Express it’s kind of a weird legacy API inconsistency because you can do `app.get` for a route as well which is confusing
3. It might help us decouple from Express a bit more instead of relying on the `.get` and `.set` functionality.
4. It gives a central place to access config values so you can dynamically set and get them. Basically a basic synchronous in memory service.
5. `app.config` is a bit more explicit, especially for people that are new to Feathers/Express

### To get this done

-  [ ] Assign the node-config instance to `app.config`
-  [ ] Alias Express' `app.get` and `app.set` to `app.config.get` and `app.config.set` except for when registering an Express `get` route. This might mean implementing with the Buzzard release when the `engine` adapters are more established.

## Related

https://github.com/feathersjs/feathers/issues/258

**Comment by daffl** [comment]
Our v3 version of Feathers decoupled from Express still supports the normal `app.get` and `app.set` so I don't think this super relevant anymore.
