### ISSUE TITLE
Config adding a value of userName in runtime its overwritten to the OS name

### ISSUE THREAD

**Issue by axmad22** [feathersjs/configuration#58]
I added the auth config values to the config files, and for the local when I set the usernameField to use userName instead of email in run-time it replaces the **usernameField** value to my PC name. If I add anything else it works but not username.
```
 local: {
      entity: 'user',
      usernameField: 'userName',
      passwordField: 'password'
  }

// becomes 

local: {
      entity: 'user',
      usernameField: 'MyPcName',
      passwordField: 'password'
  }
```

**Comment by daffl** [comment]
It will first try to use the environment variable `username` and fill it in if it exists. If you do not want that [escape with \](https://docs.feathersjs.com/api/configuration.html#variable-types).

```js
 local: {
      entity: 'user',
      usernameField: '\userName',
      passwordField: 'password'
  }
```
